### ISSUE TITLE
Cant use on Oculus

### ISSUE THREAD

**Issue by uurha** [thanh-nguyen-kim/Unity_Android_Screen_Recorder#16]
Hi. I'm tying to record screen data from Oculus but all time receiving [errors](https://pastebin.com/7m54dFNM), do you have any suggestions.

[AndroidManifest.txt](https://github.com/thanh-nguyen-kim/Unity_Android_Screen_Recorder/files/5674199/AndroidManifest.txt)

This is a bit modified AndroidManifest.

**Comment by uurha** [comment]
Also I use AndroidManifest from your project but it's not working ;-;

**Comment by thanh-nguyen-kim** [comment]
Oculus sdk might override default Unity Activity thus cause this bug. I will take a look but it may take time.

**Comment by eusebiu** [comment]
Hey! Any updates on this? I am also interested! Thanks!
My manifest:
`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:installLocation="auto">
  <application android:label="@string/app_name" android:icon="@mipmap/app_icon" android:allowBackup="false">
    <activity android:theme="@android:style/Theme.Black.NoTitleBar.Fullscreen" 
			  android:configChanges="locale|fontScale|keyboard|keyboardHidden|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode" 
			  android:launchMode="singleTask"
			  android:name="com.unity3d.player.UnityPlayerActivity" 
			  android:excludeFromRecents="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <meta-data android:name="com.oculus.vr.focusaware" android:value="true" />
    </activity>
    <meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />
    <meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only" />
  </application>
  <uses-feature android:name="android.hardware.vr.headtracking" android:version="1" android:required="true" />
  <uses-feature android:name="oculus.software.handtracking" android:required="false" />
  <uses-permission android:name="com.oculus.permission.HAND_TRACKING" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
</manifest>`

**Comment by eusebiu** [comment]
I was able to make it work on Oculus but it now gives me an exception when starting the service:
Error Unity AndroidJavaException: java.lang.IllegalStateException: System services not available to Activities before onCreate()
Error Unity java.lang.IllegalStateException: System services not available to Activities before onCreate()
Error Unity 	at android.app.Activity.getSystemService(Activity.java:6655)
Error Unity 	at com.setik.androidutils.AndroidUtils.startRecording(AndroidUtils.java:137)

The sample is assuming that the main Activity is the AndroidUtils one and parts of the code is using this assumption, like:
```
androidRecorder = unityClass.GetStatic<AndroidJavaObject>("currentActivity");
androidRecorder.Call("setUpSaveFolder","Tee");
```

**Comment by ti-hardikshah** [comment]
@eusebiu Did you able to record with audio ? I am looking for same ...

**Comment by eusebiu** [comment]
Nope, gave up!
